"""Data models module"""

from .schemas import (
    BRONZE_CUSTOMERS_SCHEMA,
    BRONZE_ORDERS_SCHEMA,
    BRONZE_PRODUCTS_SCHEMA,
    CUSTOMER_CDC_SCHEMA,
    DAILY_SALES_KPI_SCHEMA,
    DIM_CUSTOMER_SCHEMA,
    DIM_PRODUCT_SCHEMA,
    FACT_ORDERS_SCHEMA,
    QUARANTINE_SCHEMA,
    SILVER_CUSTOMERS_SCHEMA,
    SILVER_ORDERS_SCHEMA,
    SILVER_PRODUCTS_SCHEMA,
)

__all__ = [
    "BRONZE_CUSTOMERS_SCHEMA",
    "BRONZE_PRODUCTS_SCHEMA",
    "BRONZE_ORDERS_SCHEMA",
    "CUSTOMER_CDC_SCHEMA",
    "SILVER_CUSTOMERS_SCHEMA",
    "SILVER_PRODUCTS_SCHEMA",
    "SILVER_ORDERS_SCHEMA",
    "DIM_CUSTOMER_SCHEMA",
    "DIM_PRODUCT_SCHEMA",
    "FACT_ORDERS_SCHEMA",
    "DAILY_SALES_KPI_SCHEMA",
    "QUARANTINE_SCHEMA",
]
